重写github actions脚本，使用jb官方脚本

diff --git a/.github/workflows/jbr-linux-x64.yml b/.github/workflows/jbr-linux-x64.yml
--- a/.github/workflows/jbr-linux-x64.yml
+++ b/.github/workflows/jbr-linux-x64.yml
@@ -16,26 +16,42 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-20.04
     steps:
     - name: Clone Repository
-      uses: actions/checkout@v1
+      uses: actions/checkout@v2.4.0
 
-    - name: Normalize tag name
-      id: normalize-tag
+    - name: Generate Variables
+      id: vars
       run: |
         ref="${{ inputs.ref }}"
         if [[ "$ref" != jbr* ]]; then
-          ref="jbr$ref"
+          echo "Invalid tag name: $ref"
+          exit 1
         fi
-        echo ::set-output name=ref::"$ref"
+
+        JBSDK_VERSION=$(sed -E 's/^jbr([0-9_]+)b.*$/\1/' <<< "$ref")
+        echo ::set-output name=JBSDK_VERSION::"$JBSDK_VERSION"
+
+        build_number=$(sed -E 's/^jbr[0-9_]+b([0-9.]+)$/\1/' <<< "$ref")
+        echo ::set-output name=build_number::"$build_number"
+
+        bundle_type=jcef
+        echo ::set-output name=bundle_type::"$bundle_type"
+
+        mkdir official_build && cd official_build
+        curl -sfL -m 600 "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_${bundle_type}-${JBSDK_VERSION}-linux-x64-b${build_number}.tar.gz" | tar --strip-components=1 -zxf -
+        JDK_BUILD_NUMBER=$(bin/java -version 2>&1 | grep -oE '\(build [0-9.]+\+[0-9]+-b[0-9.]+\)$' | sed -E 's/^.+\+([0-9]+)-b.+$/\1/')
+        echo ::set-output name=JDK_BUILD_NUMBER::"$JDK_BUILD_NUMBER"
+        cd .. && rm -rf official_build
+
+        JBR_BASE_NAME=jbr_${bundle_type}-${JBSDK_VERSION}
+        echo ::set-output name=JBR::"${JBR_BASE_NAME}-linux-x64-b${build_number}"
 
     - name: Init Build Dependencies
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
-        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
-        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/lib/jvm/
         sudo -E apt-get update -y
         sudo -E apt-get install -y ant autoconf bison build-essential cmake flex git gperf ksh \
             libasound2-dev libavcodec-dev libavformat-dev libcups2-dev libfontconfig1-dev \
@@ -43,7 +59,6 @@ jobs:
             libgtk2.0-dev libgtk-3-dev libjpeg-dev libpng-dev libudev-dev libx11-dev libxext-dev \
             libxml2-dev libxrandr-dev libxrender-dev libxslt1-dev libxt-dev libxtst-dev libxxf86vm-dev \
             make mercurial openjdk-11-jdk pkg-config ruby tree x11proto-core-dev x11proto-xf86vidmode-dev zip
-        sudo -E apt-get autoremove -y --purge
         sudo -E apt-get clean -y
 
     - name: Compile JCEF
@@ -60,13 +75,6 @@ jobs:
         cd ../jb/tools/linux && chmod +x *
         ./build.sh all
 
-    - name: List Paths
-      run: |
-        cd jcef
-        ls -a
-        echo
-        tree -a
-
     - name: Patch & Compile JetBrainsRuntime with JCEF
       env:
         JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
@@ -76,49 +84,9 @@ jobs:
         git clone --depth 1 -b "${{ inputs.ref }}" --single-branch https://github.com/JetBrains/JetBrainsRuntime.git
         cd JetBrainsRuntime
         git log -1
-        git apply -p0 < jb/project/tools/patches/add_jcef_module.patch
-        mv ../idea.patch ./
-        patch -p1 < idea.patch
-        sh ./configure --disable-warnings-as-errors --with-import-modules=../jcef/out/linux64/modular-sdk
-        make images
-
-    - name: List Paths
-      run: |
-        cd JetBrainsRuntime
-        ls -a
-        echo
-        tree -a
-
-    - name: Reduce Size
-      env:
-        BASE_DIR: build/linux-x86_64-normal-server-release/images
-        JBR_BUNDLE: jbr_jcef
-        JCEF_PATH: ../jcef/jcef_build/native/Release
-      run: |
-        cd JetBrainsRuntime
-        cat modules.list > modules_tmp.list
-        rm -rf ${BASE_DIR}/${JBR_BUNDLE}
-        ${BASE_DIR}/jdk/bin/jlink \
-            --module-path ${BASE_DIR}/jdk/jmods --no-man-pages --compress=2 \
-            --add-modules $(xargs < modules_tmp.list | sed s/" "//g) --output $BASE_DIR/$JBR_BUNDLE
-        cp -R $BASE_DIR/$JBR_BUNDLE $BASE_DIR/jbr
-        rsync -av ${JCEF_PATH}/ $BASE_DIR/$JBR_BUNDLE/lib --exclude="modular-sdk"
-        grep -v "^JAVA_VERSION" ${BASE_DIR}/jdk/release | grep -v "^MODULES" >> $BASE_DIR/$JBR_BUNDLE/release
-        rm -rf ${BASE_DIR}/jbr
-        cp -R ${BASE_DIR}/${JBR_BUNDLE} ${BASE_DIR}/jbr
-
-    - name: Package Artifact
-      run: |
-        cd JetBrainsRuntime/build/linux-x86_64-normal-server-release/images
-        mv jbr ${{ steps.normalize-tag.outputs.ref }}
-        zip -r ${{ steps.normalize-tag.outputs.ref }}-linux-x64.zip ./${{ steps.normalize-tag.outputs.ref }}/*
-        mv ${{ steps.normalize-tag.outputs.ref }}-linux-x64.zip ../../../../
-
-    - name: Upload Artifact
-      uses: actions/upload-artifact@master
-      with:
-        name: ${{ steps.normalize-tag.outputs.ref }}.zip
-        path: ${{ steps.normalize-tag.outputs.ref }}-linux-x64.zip
+        patch -p1 < ../idea.patch
+        mkdir -p jcef_linux_x64 && cd jcef_linux_x64 && tar -xf ../../jcef/jcef_linux_x64.tar.gz && cd ..
+        jb/project/tools/linux/scripts/mkimages_x64.sh '${{ steps.vars.outputs.JBSDK_VERSION }}' '${{ steps.vars.outputs.JDK_BUILD_NUMBER }}' '${{ steps.vars.outputs.build_number }}' '${{ steps.vars.outputs.bundle_type }}'
 
     - name: Create Release
       id: create_release
@@ -139,7 +107,7 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ./${{ steps.normalize-tag.outputs.ref }}-linux-x64.zip
-        asset_name: ${{ steps.normalize-tag.outputs.ref }}-linux-x64.zip
-        asset_content_type: application/zip
+        asset_path: JetBrainsRuntime/${{ steps.vars.outputs.JBR }}.tar.gz
+        asset_name: ${{ steps.vars.outputs.JBR }}.tar.gz
+        asset_content_type: application/gzip
 
